# Generated by Django 3.0.1 on 2020-01-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200118_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
    ]
